### ISSUE TITLE
why we need to sort the attrs?

### ISSUE THREAD

**Issue by vhoyer** [psalaets/vue-sfc-descriptor-to-string#2]

**Comment by psalaets** [comment]
I don't remember why I did that haha. I think it was because I wasn't sure if object properties had a defined iteration order back then.

We could probably take out the sorting now.

Is it causing a problem for you?

**Comment by vhoyer** [comment]
It kinda is, people here on the company are aperrently very passionate about their attribute order, I don't wanna mess with their projects (I'm writing a codemod tool)

**Comment by psalaets** [comment]
This change was published as version 3.0.0
